version: '3.1'

 volumes:
   nfs-volume:
     driver: local
     driver_opts:
       type: nfs
       device: ":pg_data"
       o: addr=<host>,rw

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - nfs-volume:/var/lib/postgresql/data