version: '3.7'

services:
  product-service:
    build: ../nexct-approval-service
    volumes:
      - ../nexct-approval-service:/usr/src/app
    environment:
        POSTGRES_DB_PORT: "5432"
        POSTGRES_DB_HOST: "localhost"
        POSTGRES_PASSWORD:
        POSTGRES_USER: postgres
        POSTGRES_DB: pims
    networks:
        - product_service_network

networks:
    product_service_network:
        driver: bridge